# Generated by Django 4.1.3 on 2022-12-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default_pfp.jpg', upload_to=''),
        ),
    ]
