# Generated by Django 4.1.3 on 2022-12-18 18:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=256)),
                ('state', models.JSONField()),
                ('players', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, size=None)),
                ('image', models.ImageField(default='default_game_pic.jpg', upload_to='')),
                ('gm', models.BigIntegerField()),
            ],
        ),
    ]
