# Generated by Django 4.1.3 on 2022-12-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=256)),
                ('state', models.JSONField()),
                ('players', models.JSONField()),
            ],
        ),
    ]
