# Generated by Django 4.1.3 on 2022-12-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(default='default_game_pic.png', upload_to=''),
        ),
    ]
